### ISSUE TITLE
MalformedPolicyDocument: The policy failed legacy parsing

### ISSUE THREAD

**Issue by n0um3n4** [danschultzer/elixir-terraform-aws-ecs-example#1]
```
│   with aws_iam_role.github_actions_ecs,
│   on gha.tf line 72, in resource "aws_iam_role" "github_actions_ecs":
│   72: resource "aws_iam_role" "github_actions_ecs" {
```

Is this working for ya? I'm doing just exactly what it is there and I'm getting this error.

any ideas what could it be? 

@danschultzer Great work, btw! 

https://github.com/danschultzer/elixir-terraform-aws-ecs-example/blob/8c41492188d9f9a23279fef5be7053dd9c211b21/my_project/.infrastructure/workspaces/default/gha.tf#L72

**Comment by danschultzer** [comment]
Yeah it’s used in production.

AWS errors are impossible to decipher, but my guess would be that some variable being injected has invalid characters. It might be the `github_repository`. It should read like: `danschultzer/elixir-terraform-aws-ecs-example`

If all the variables are good it might be something in terraform, as this is terraform generating the policy. I haven’t had any issues though.

**Comment by n0um3n4** [comment]
> Yeah it’s used in production.
> 
> AWS errors are impossible to decipher, but my guess would be that some variable being injected has invalid characters. It might be the `github_repository`. It should read like: `danschultzer/elixir-terraform-aws-ecs-example`
> 
> If all the variables are good it might be something in terraform, as this is terraform generating the policy. I haven’t had any issues though.

Let me take a look at that! Thanks! 🙏🏻

**Comment by danschultzer** [comment]
Let me know if you figured out what it was, might help others who experience this error 😁

**Comment by n0um3n4** [comment]
> Let me know if you figured out what it was, might help others who experience this error 😁

But of course it was the repo... it was me... 🤦🏻‍♂️ the account id was wrong.
